# Generated by Django 4.0 on 2022-01-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, choices=[('RANGPUR', 'Rangpur'), ('DHAKA', 'Dhaka'), ('DINAJPUR', 'Dinajpur')], max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('clientLogo', models.ImageField(upload_to='clientLogos/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('invoiceTotal', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('paymentStatus', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('DUE', 'Due'), ('OVERDUE', 'Overdue')], max_length=100, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoice.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, choices=[('TK', 'TK'), ('USD', '$'), ('EUR', 'Eur')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clientLogos/')),
                ('uniqueId', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice.invoice')),
            ],
        ),
    ]
