# Generated by Django 4.0 on 2022-01-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('addressLine1', models.CharField(max_length=200, verbose_name='Address')),
                ('postalCode', models.CharField(max_length=20, verbose_name='Postal code')),
                ('province', models.CharField(choices=[('RANGPUR', 'Rangpur'), ('DHAKA', 'Dhaka'), ('DINAJPUR', 'Dinajpur')], max_length=100, verbose_name='Province')),
                ('phoneNumber', models.CharField(max_length=100, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('clientLogo', models.ImageField(upload_to='clientLogos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inv number')),
                ('invoiceTitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice title')),
                ('dueDate', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('invoiceTotal', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Invoice total')),
                ('paymentStatus', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('DUE', 'Due'), ('OVERDUE', 'Overdue')], max_length=100, null=True, verbose_name='Payment status')),
                ('uniqueId', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice id')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last updated')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoice.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='Product Title', max_length=200, verbose_name='Product name')),
                ('description', models.TextField(default='Product descriptions..', max_length=4000, verbose_name='Description')),
                ('quantity', models.CharField(default=0, max_length=200, verbose_name='Quantity')),
                ('price', models.CharField(default=0, max_length=200, verbose_name='Price')),
                ('currency', models.CharField(choices=[('TK', 'TK'), ('USD', '$'), ('EUR', 'Eur')], default='TK', max_length=20, verbose_name='Currency')),
                ('image', models.ImageField(upload_to='clientLogos/', verbose_name='Product image')),
                ('uniqueId', models.CharField(max_length=200, verbose_name='Product id')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice.invoice', verbose_name='Invoice')),
            ],
        ),
    ]
