# Generated by Django 4.0 on 2021-12-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, choices=[('RANGPUR', 'Rangpur'), ('DHAKA', 'Dhaka'), ('DINAJPUR', 'Dinajpur')], max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('clientLogo', models.ImageField(max_length=200, upload_to='clientLogos/')),
            ],
        ),
    ]
