# Generated by Django 4.0 on 2022-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company')),
                ('addressLine', models.CharField(max_length=400, verbose_name='Address')),
                ('postalCode', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('province', models.CharField(choices=[('RANGPUR', 'Rangpur'), ('DHAKA', 'Dhaka'), ('DINAJPUR', 'Dinajpur')], max_length=100, verbose_name='Province')),
                ('phoneNumber', models.CharField(max_length=100, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('clientLogo', models.ImageField(upload_to='clientLogos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
