# Generated by Django 4.0 on 2022-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('TK', 'TK'), ('USD', '$'), ('EUR', 'Eur')], default='TK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Product descriptions..', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productTitle',
            field=models.CharField(blank=True, default='Product Title', max_length=200, null=True),
        ),
    ]
