# Generated by Django 4.0 on 2022-01-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='title',
            new_name='invoiceTitle',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='productTitle',
        ),
    ]
