# Generated by Django 4.0 on 2022-01-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_product_currency_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Product descriptions..', max_length=4000, null=True),
        ),
    ]
