# Generated by Django 4.0 on 2022-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_rename_title_invoice_invoicetitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceTotal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
