# Generated by Django 4.0 on 2022-01-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoice.product'),
        ),
    ]
